# Generated by Django 5.2.4 on 2025-08-04 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this audit log entry', primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('profile_update', 'Profile Update'), ('profile_view', 'Profile View'), ('password_change', 'Password Change'), ('email_verification', 'Email Verification'), ('login', 'User Login'), ('logout', 'User Logout'), ('registration', 'User Registration'), ('account_lock', 'Account Lock'), ('account_unlock', 'Account Unlock'), ('mfa_setup', 'MFA Setup'), ('mfa_disable', 'MFA Disable'), ('oauth_link', 'OAuth Account Link'), ('oauth_unlink', 'OAuth Account Unlink'), ('data_export', 'Data Export'), ('data_deletion', 'Data Deletion'), ('permission_change', 'Permission Change'), ('role_assignment', 'Role Assignment'), ('api_access', 'API Access'), ('security_event', 'Security Event'), ('system_event', 'System Event')], help_text='Type of event being logged', max_length=50)),
                ('event_description', models.TextField(help_text='Human-readable description of the event')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', help_text='Severity level of the event', max_length=20)),
                ('user_email', models.EmailField(blank=True, help_text='Email of the user (stored for deleted users)', max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the request', null=True)),
                ('request_id', models.CharField(blank=True, help_text='Unique request identifier for correlation', max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, help_text='Session identifier', max_length=255, null=True)),
                ('object_id', models.CharField(blank=True, help_text='ID of the related object', max_length=255, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Previous values before the change')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New values after the change')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the event')),
                ('retention_until', models.DateTimeField(blank=True, help_text='When this audit log should be deleted for compliance', null=True)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Whether this log contains sensitive information')),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the related object', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('impersonated_by', models.ForeignKey(blank=True, help_text='User who was impersonating (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_auditlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileChangeHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this change record', primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text='Name of the field that was changed', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value of the field', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value of the field', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the change request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the change request', null=True)),
                ('request_id', models.CharField(blank=True, help_text='Request ID for correlation', max_length=255, null=True)),
                ('audit_log', models.ForeignKey(help_text='Related audit log entry', on_delete=django.db.models.deletion.CASCADE, related_name='profile_changes', to='core.auditlog')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change (if different)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User whose profile was changed', on_delete=django.db.models.deletion.CASCADE, related_name='profile_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Change History',
                'verbose_name_plural': 'Profile Change Histories',
                'db_table': 'audit_profilechangehistory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type', '-created_at'], name='audit_audit_event_t_5dda62_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', '-created_at'], name='audit_audit_severit_49184d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', '-created_at'], name='audit_audit_ip_addr_ff6f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['request_id'], name='audit_audit_request_06fe30_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['session_id'], name='audit_audit_session_10dd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['retention_until'], name='audit_audit_retenti_696a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='profilechangehistory',
            index=models.Index(fields=['user', '-created_at'], name='audit_profi_user_id_5704f2_idx'),
        ),
        migrations.AddIndex(
            model_name='profilechangehistory',
            index=models.Index(fields=['field_name', '-created_at'], name='audit_profi_field_n_6f1215_idx'),
        ),
        migrations.AddIndex(
            model_name='profilechangehistory',
            index=models.Index(fields=['changed_by', '-created_at'], name='audit_profi_changed_8da505_idx'),
        ),
        migrations.AddIndex(
            model_name='profilechangehistory',
            index=models.Index(fields=['audit_log'], name='audit_profi_audit_l_69b749_idx'),
        ),
        migrations.AddIndex(
            model_name='profilechangehistory',
            index=models.Index(fields=['-created_at'], name='audit_profi_created_87ee85_idx'),
        ),
    ]
